const React = require('react');
const BillResultSummary = require('./BillResultSummary.jsx')

class SearchResults extends React.Component {
  render() {
    return (
      <SearchResultsPresentational searchResults={this.props.billResults} />
    );
  }

}


class SearchResultsPresentational extends React.Component {
  render() {
    let billResultComponents = this.props.searchResults.map(
      function(bill) {
        return <BillResultSummary key={bill.bill_id} info={bill} />;
      });

    return (
      <div>
        {billResultComponents}
      </div>
    );
  }
}

module.exports = SearchResults;

SearchResults.defaultProps = {
  billResults: [
    {
      "bill_id": "hr1761-112",
      "cosponsor_ids": [
        "B001245",
        "C001036",
        "C000380",
        "F000010",
        "F000030",
        "F000116",
        "G000551",
        "G000569",
        "H001050",
        "H001042",
        "L000397",
        "M000133",
        "M000725",
        "M000933",
        "R000053",
        "S001177",
        "Y000033"
      ],
      "sponsor": {
        "birthday": "1959-04-26",
        "bioguide_id": "P000596",
        "gender": "M",
        "fec_ids": [
          "H8PR00062"
        ],
        "office": "1213 Longworth House Office Building",
        "title": "Com",
        "crp_id": "N00029168",
        "chamber": "house",
        "state_name": "Puerto Rico",
        "nickname": null,
        "term_end": "2017-01-03",
        "state": "PR",
        "fax": "202-225-2154",
        "twitter_id": "pedropierluisi",
        "first_name": "Pedro",
        "ocd_id": "ocd-division/country:us/territory:pr",
        "website": "http://pierluisi.house.gov",
        "name_suffix": null,
        "contact_form": "http://pierluisi.house.gov/contact/email-me",
        "last_name": "Pierluisi",
        "thomas_id": "01953",
        "in_office": true,
        "middle_name": "R.",
        "youtube_id": "PierluisiCongress",
        "facebook_id": "55139978107",
        "term_start": "2013-01-03",
        "phone": "202-225-2615",
        "district": 0,
        "votesmart_id": 110894,
        "govtrack_id": "412306",
        "party": "D"
      },
      "related_bill_ids": [],
      "last_action_at": "2011-07-28",
      "keywords": [
        "Department of the Interior",
        "Executive agency funding and structure",
        "Foreign aid and international relief",
        "International organizations and cooperation",
        "Marine and coastal resources, fisheries",
        "Public lands and natural resources",
        "Reptiles",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2011-05-05",
      "sponsor_id": "P000596",
      "short_title": "Marine Turtle Conservation Reauthorization Act of 2011",
      "urls": {
        "congress": "http://beta.congress.gov/bill/112th/house-bill/1761",
        "govtrack": "http://www.govtrack.us/congress/bills/112/hr1761",
        "opencongress": "http://www.opencongress.org/bill/112-h1761/show"
      },
      "chamber": "house",
      "official_title": "To reauthorize the Marine Turtle Conservation Act of 2004, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Marine Turtle Conservation Reauthorization Act of 2011 - Expands marine turtle conservation assistance under the Marine Turtle Conservation Act of 2004 to include the United States and its territories. Authorizes appropriations to the Marine Turtle Conservation Fund for FY2012-FY2017. Authorizes an increase in the amount available from the Fund for administrative expenses. Requires not less than 20% of amounts made available from the Fund for any fiscal year to be used for projects relating to the conservation of marine turtles in the United States.",
      "search": {
        "score": 0.83150685,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr1329-113",
      "cosponsor_ids": [
        "B001245",
        "C001036",
        "C000380",
        "F000010",
        "F000030",
        "G000551",
        "G000569",
        "L000397",
        "M000725",
        "M000933",
        "R000053",
        "S001177",
        "V000132",
        "Y000033"
      ],
      "sponsor": {
        "birthday": "1959-04-26",
        "bioguide_id": "P000596",
        "gender": "M",
        "fec_ids": [
          "H8PR00062"
        ],
        "office": "1213 Longworth House Office Building",
        "title": "Com",
        "crp_id": "N00029168",
        "chamber": "house",
        "state_name": "Puerto Rico",
        "nickname": null,
        "term_end": "2017-01-03",
        "state": "PR",
        "fax": "202-225-2154",
        "twitter_id": "PedroPierluisi",
        "first_name": "Pedro",
        "ocd_id": "ocd-division/country:us/territory:pr",
        "website": "http://pierluisi.house.gov",
        "name_suffix": null,
        "contact_form": "https://pierluisi.house.gov/contact/email-me",
        "last_name": "Pierluisi",
        "thomas_id": "01953",
        "in_office": true,
        "middle_name": "R.",
        "youtube_id": "PierluisiCongress",
        "facebook_id": "55139978107",
        "term_start": "2013-01-03",
        "phone": "202-225-2615",
        "district": 0,
        "votesmart_id": 110894,
        "oc_email": "Rep.Pierluisi@opencongress.org",
        "govtrack_id": "412306",
        "party": "D"
      },
      "related_bill_ids": [],
      "last_action_at": "2013-04-11",
      "keywords": [
        "Department of the Interior",
        "Executive agency funding and structure",
        "Foreign aid and international relief",
        "International organizations and cooperation",
        "Marine and coastal resources, fisheries",
        "Public lands and natural resources",
        "Reptiles",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2013-03-21",
      "sponsor_id": "P000596",
      "short_title": "Marine Turtle Conservation Reauthorization Act of 2013",
      "urls": {
        "congress": "http://beta.congress.gov/bill/113th/house-bill/1329",
        "govtrack": "https://www.govtrack.us/congress/bills/113/hr1329",
        "opencongress": "http://www.opencongress.org/bill/hr1329-113"
      },
      "chamber": "house",
      "official_title": "To reauthorize the Marine Turtle Conservation Act of 2004, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Marine Turtle Conservation Reauthorization Act of 2013 - Amends the Marine Turtle Conservation Act of 2004 to provide for its applicability to the United States (currently, the Act applies to foreign countries).\n\nAuthorizes appropriations to the Marine Turtle Conservation Fund for FY2014-FY2018. Authorizes an increase in the amount available from the Fund for administrative expenses. Requires not less than 20% of amounts made available from the Fund for any fiscal year to be used for projects relating to the conservation of marine turtles in the United States.",
      "search": {
        "score": 0.77280617,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr2276-114",
      "cosponsor_ids": [
        "B000911",
        "C001066",
        "F000462",
        "G000575",
        "H000324",
        "P000599",
        "W000797",
        "W000808"
      ],
      "sponsor": {
        "birthday": "1983-03-30",
        "bioguide_id": "M001191",
        "gender": "M",
        "fec_ids": [
          "H2FL22072"
        ],
        "office": "211 Cannon House Office Building",
        "title": "Rep",
        "crp_id": "N00033091",
        "chamber": "house",
        "state_name": "Florida",
        "nickname": null,
        "term_end": "2017-01-03",
        "state": "FL",
        "fax": "202-225-8398",
        "twitter_id": "RepMurphyFL",
        "first_name": "Patrick",
        "ocd_id": "ocd-division/country:us/state:fl/cd:18",
        "website": "http://patrickmurphy.house.gov",
        "name_suffix": null,
        "contact_form": "http://patrickmurphy.house.gov/contact/",
        "icpsr_id": 21319,
        "last_name": "Murphy",
        "thomas_id": "02117",
        "in_office": true,
        "middle_name": null,
        "youtube_id": "RepPatrickMurphyFL",
        "facebook_id": "317735028342371",
        "term_start": "2015-01-06",
        "phone": "202-225-3026",
        "district": 18,
        "votesmart_id": 137652,
        "oc_email": "Rep.Patrickmurphy@opencongress.org",
        "govtrack_id": "412527",
        "party": "D"
      },
      "related_bill_ids": [
        "hr2279-114",
        "s1171-114"
      ],
      "last_action_at": "2015-06-04",
      "keywords": [
        "Atlantic Ocean",
        "Energy",
        "Environmental assessment, monitoring, research",
        "Fishes",
        "Florida",
        "Mammals",
        "Marine and coastal resources, fisheries",
        "Oil and gas",
        "Reptiles",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2015-05-12",
      "sponsor_id": "M001191",
      "short_title": "Seismic Moratorium Act",
      "urls": {
        "congress": "http://beta.congress.gov/bill/114th/house-bill/2276",
        "govtrack": "https://www.govtrack.us/congress/bills/114/hr2276",
        "opencongress": "https://www.opencongress.org/bill/hr2276-114"
      },
      "chamber": "house",
      "official_title": "To establish a moratorium on oil and gas-related seismic activities off the coastline of the State of Florida, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Seismic Moratorium Act\n\nThis bill prohibits conducting geological or geophysical activities in support of oil or gas exploration and development in any area located within a specified exclusive economic zone located off the coastline of Florida.\n\nThis moratorium shall only be terminated if the Administrator of the National Oceanic and Atmospheric Administration (of the Department of Commerce) determines that the reasonably foreseeable impacts of such activities are minimal to individuals or populations of marine mammals, sea turtles, or fish.\n\nThese geological or geophysical activities are described in the final programmatic environmental impact statement of the Bureau of Ocean Energy Management (of the Department of the Interior) entitled \"Atlantic OCS Proposed Geological and Geophysical Activities, Mid-Atlantic and South Atlantic Planning Areas,\" completed February 2014.",
      "search": {
        "score": 0.6440052000000001,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr2279-114",
      "cosponsor_ids": [
        "M001191"
      ],
      "sponsor": {
        "birthday": "1947-12-18",
        "bioguide_id": "P000599",
        "gender": "M",
        "fec_ids": [
          "H8FL15107"
        ],
        "office": "120 Cannon House Office Building",
        "title": "Rep",
        "crp_id": "N00029662",
        "chamber": "house",
        "state_name": "Florida",
        "nickname": null,
        "term_end": "2017-01-03",
        "state": "FL",
        "fax": "202-225-3516",
        "twitter_id": "CongBillPosey",
        "first_name": "Bill",
        "ocd_id": "ocd-division/country:us/state:fl/cd:8",
        "website": "http://posey.house.gov",
        "name_suffix": null,
        "contact_form": "https://posey.house.gov/forms/writeyourrep/",
        "icpsr_id": 20909,
        "last_name": "Posey",
        "thomas_id": "01915",
        "in_office": true,
        "middle_name": null,
        "youtube_id": "CongressmanPosey",
        "facebook_id": "100000080395369",
        "term_start": "2015-01-06",
        "phone": "202-225-3671",
        "district": 8,
        "votesmart_id": 24280,
        "oc_email": "Rep.Posey@opencongress.org",
        "govtrack_id": "412309",
        "party": "R"
      },
      "related_bill_ids": [
        "hr2276-114",
        "s1171-114"
      ],
      "last_action_at": "2015-06-04",
      "keywords": [
        "Atlantic Ocean",
        "Energy",
        "Environmental assessment, monitoring, research",
        "Fishes",
        "Florida",
        "Mammals",
        "Marine and coastal resources, fisheries",
        "Oil and gas",
        "Reptiles",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2015-05-12",
      "sponsor_id": "P000599",
      "short_title": "Seismic Moratorium Act",
      "urls": {
        "congress": "http://beta.congress.gov/bill/114th/house-bill/2279",
        "govtrack": "https://www.govtrack.us/congress/bills/114/hr2279",
        "opencongress": "https://www.opencongress.org/bill/hr2279-114"
      },
      "chamber": "house",
      "official_title": "To establish a moratorium on oil and gas-related seismic activities off the coastline of the State of Florida, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Seismic Moratorium Act\n\nThis bill prohibits conducting geological or geophysical activities in support of oil or gas exploration and development in any area located within a specified exclusive economic zone located off the coastline of Florida.\n\nThis moratorium shall only be terminated if the Administrator of the National Oceanic and Atmospheric Administration (of the Department of Commerce) determines that the reasonably foreseeable impacts of such activities are minimal to individuals or populations of marine mammals, sea turtles, or fish.\n\nThese geological or geophysical activities are described in the final programmatic environmental impact statement of the Bureau of Ocean Energy Management (of the Department of the Interior) entitled \"Atlantic OCS Proposed Geological and Geophysical Activities, Mid-Atlantic and South Atlantic Planning Areas,\" completed February 2014.",
      "search": {
        "score": 0.6366526,
        "type": "bill"
      }
    },
    {
      "bill_id": "s1171-114",
      "cosponsor_ids": [],
      "sponsor": {
        "birthday": "1942-09-29",
        "bioguide_id": "N000032",
        "gender": "M",
        "fec_ids": [
          "S8FL00166"
        ],
        "office": "716 Hart Senate Office Building",
        "senate_class": 1,
        "title": "Sen",
        "crp_id": "N00009926",
        "chamber": "senate",
        "state_name": "Florida",
        "nickname": null,
        "term_end": "2019-01-03",
        "state": "FL",
        "fax": "202-228-2183",
        "twitter_id": "SenBillNelson",
        "first_name": "Bill",
        "ocd_id": "ocd-division/country:us/state:fl",
        "website": "https://www.billnelson.senate.gov",
        "name_suffix": null,
        "contact_form": "http://www.billnelson.senate.gov/contact-bill",
        "icpsr_id": 14651,
        "last_name": "Nelson",
        "thomas_id": "00859",
        "in_office": true,
        "lis_id": "S282",
        "middle_name": null,
        "youtube_id": "senbillnelson",
        "facebook_id": null,
        "state_rank": "senior",
        "term_start": "2013-01-03",
        "phone": "202-224-5274",
        "district": null,
        "votesmart_id": 1606,
        "oc_email": "Sen.Billnelson@opencongress.org",
        "govtrack_id": "300078",
        "party": "D"
      },
      "related_bill_ids": [
        "hr2276-114",
        "hr2279-114"
      ],
      "last_action_at": "2015-04-30",
      "keywords": [
        "Atlantic Ocean",
        "Energy",
        "Environmental assessment, monitoring, research",
        "Fishes",
        "Florida",
        "Mammals",
        "Marine and coastal resources, fisheries",
        "Oil and gas",
        "Reptiles",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2015-04-30",
      "sponsor_id": "N000032",
      "short_title": "Seismic Moratorium Act",
      "urls": {
        "congress": "http://beta.congress.gov/bill/114th/senate-bill/1171",
        "govtrack": "https://www.govtrack.us/congress/bills/114/s1171",
        "opencongress": "https://www.opencongress.org/bill/s1171-114"
      },
      "chamber": "senate",
      "official_title": "A bill to establish a moratorium on oil and gas-related seismic activities off the coastline of the State of Florida, and for other purposes.",
      "bill_type": "s",
      "summary_short": "Seismic Moratorium Act\n\nThis bill prohibits conducting geological or geophysical activities in support of oil or gas exploration and development in any area located within a specified exclusive economic zone located off the coastline of Florida.\n\nThis moratorium shall only be terminated if the Administrator of the National Oceanic and Atmospheric Administration (of the Department of Commerce) determines that the reasonably foreseeable impacts of such activities are minimal to individuals or populations of marine mammals, sea turtles, or fish.\n\nThese geological or geophysical activities are described in the final programmatic environmental impact statement of the Bureau of Ocean Energy Management (of the Department of the Interior) entitled \"Atlantic OCS Proposed Geological and Geophysical Activities, Mid-Atlantic and South Atlantic Planning Areas,\" completed February 2014.",
      "search": {
        "score": 0.6366526,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr5155-111",
      "cosponsor_ids": [
        "F000339",
        "O000107"
      ],
      "sponsor": {
        "birthday": "1943-02-10",
        "bioguide_id": "J000255",
        "gender": "M",
        "fec_ids": [
          "H2NC01081"
        ],
        "office": "2333 Rayburn House Office Building",
        "title": "Rep",
        "crp_id": "N00002299",
        "chamber": "house",
        "state_name": "North Carolina",
        "nickname": null,
        "term_end": "2015-01-03",
        "state": "NC",
        "fax": "202-225-3286",
        "twitter_id": "RepWalterJones",
        "first_name": "Walter",
        "ocd_id": "ocd-division/country:us/state:nc/cd:3",
        "website": "http://jones.house.gov",
        "name_suffix": "Jr.",
        "contact_form": "http://jones.house.gov/contact-me/email-me",
        "icpsr_id": 29546,
        "last_name": "Jones",
        "thomas_id": "00612",
        "in_office": true,
        "middle_name": "B.",
        "youtube_id": "RepWalterJones",
        "facebook_id": "15083070102",
        "term_start": "2013-01-03",
        "phone": "202-225-3415",
        "district": 3,
        "votesmart_id": 21785,
        "govtrack_id": "400209",
        "party": "R"
      },
      "related_bill_ids": [],
      "last_action_at": "2010-04-29",
      "keywords": [
        "Administrative law and regulatory procedures",
        "Department of Commerce",
        "Endangered and threatened species",
        "Government investigations",
        "Marine and coastal resources, fisheries",
        "Public lands and natural resources",
        "Reptiles"
      ],
      "introduced_on": "2010-04-27",
      "sponsor_id": "J000255",
      "short_title": null,
      "urls": {
        "congress": "http://beta.congress.gov/bill/111th/house-bill/5155",
        "govtrack": "http://www.govtrack.us/congress/bills/111/hr5155",
        "opencongress": "http://www.opencongress.org/bill/111-h5155/show"
      },
      "chamber": "house",
      "official_title": "To direct the Secretary of Commerce to conduct an aerial assessment of sea turtle populations in United States waters, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Requires the Secretary of Commerce to conduct an aerial assessment of and report to Congress on the population abundance and spatial and temporal distribution of Green, Loggerhead, Leatherback, Kemp's Ridley, and Hawksbill sea turtles in state and federal waters.\n\nProhibits the Secretary from issuing any rule regarding incidental fisheries bycatch of any of such turtle species under the Endangered Species Act of 1973 (ESA) or the Magnuson-Stevens Fishery Conservation and Management Act before the report is submitted. Exempts any rule to alter or restrict use of a specific gear type in a specific fishery if the Secretary certifies that the rule is an emergency rule necessary to: (1) protect such a species from being imminently determined to be endangered primarily as a result of incidental taking by that gear type in that fishery; or (2) protect such a species that is listed as an endangered species from imminent extinction primarily as a result of incidental taking of such species by th...",
      "search": {
        "score": 0.56854105,
        "type": "bill"
      }
    },
    {
      "bill_id": "sres390-114",
      "cosponsor_ids": [
        "I000024"
      ],
      "sponsor": {
        "birthday": "1963-09-09",
        "bioguide_id": "C001088",
        "gender": "M",
        "fec_ids": [
          "S0DE00092"
        ],
        "office": "127a Russell Senate Office Building",
        "senate_class": 2,
        "title": "Sen",
        "crp_id": "N00031820",
        "chamber": "senate",
        "state_name": "Delaware",
        "nickname": null,
        "term_end": "2021-01-03",
        "state": "DE",
        "twitter_id": "SenCoonsOffice",
        "first_name": "Chris",
        "ocd_id": "ocd-division/country:us/state:de",
        "website": "https://www.coons.senate.gov",
        "name_suffix": null,
        "contact_form": "http://www.coons.senate.gov/contact/",
        "icpsr_id": 40916,
        "last_name": "Coons",
        "thomas_id": "01984",
        "in_office": true,
        "lis_id": "S337",
        "middle_name": "Andrew",
        "youtube_id": "senatorchriscoons",
        "facebook_id": "254950754518205",
        "state_rank": "junior",
        "term_start": "2015-01-06",
        "phone": "202-224-5042",
        "district": null,
        "votesmart_id": 122834,
        "oc_email": "Sen.Coons@opencongress.org",
        "govtrack_id": "412390",
        "party": "D"
      },
      "related_bill_ids": [
        "sres95-114"
      ],
      "last_action_at": "2016-03-03",
      "keywords": [
        "Animals",
        "Commemorative events and holidays",
        "Crime prevention",
        "Crimes against animals and natural resources",
        "International organizations and cooperation",
        "Smuggling and trafficking",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2016-03-03",
      "sponsor_id": "C001088",
      "short_title": null,
      "urls": {
        "congress": "http://beta.congress.gov/bill/114th/senate-resolution/390",
        "govtrack": "https://www.govtrack.us/congress/bills/114/sres390",
        "opencongress": "https://www.opencongress.org/bill/sres390-114"
      },
      "chamber": "senate",
      "official_title": "A resolution designating March 3, 2016 as \"World Wildlife Day\".",
      "bill_type": "sres",
      "summary_short": "(This measure has not been amended since it was introduced. The summary of that version is repeated here.)\n\nDesignates March 3, 2016, as World Wildlife Day. Supports: (1) raising awareness of the benefits that wildlife provides to people and the threats facing wildlife around the world; and (2) escalating the fight against wildlife crime, such as wildlife trafficking.\n\nCommends efforts of the United States to mobilize the government in a coordinated, efficient, and effective manner for progress in the fight.\n\nEncourages continued cooperation between the United States, international partners, local communities, nonprofit organizations, private industry, and other partner organizations in an effort to conserve and celebrate wildlife.",
      "search": {
        "score": 0.19133821,
        "type": "bill"
      }
    },
    {
      "bill_id": "sres346-111",
      "cosponsor_ids": [
        "C000127",
        "K000148",
        "K000374",
        "R000122",
        "W000802"
      ],
      "sponsor": {
        "birthday": "1947-02-21",
        "bioguide_id": "S000663",
        "gender": "F",
        "fec_ids": [
          "S4ME00055"
        ],
        "office": "154 Russell Senate Office Building",
        "senate_class": 1,
        "title": "Sen",
        "crp_id": "N00000480",
        "chamber": "senate",
        "state_name": "Maine",
        "nickname": null,
        "term_end": "2013-01-03",
        "state": "ME",
        "fax": "202-224-1946",
        "twitter_id": "SenatorSnowe",
        "first_name": "Olympia",
        "ocd_id": "ocd-division/country:us/state:me",
        "website": "http://snowe.senate.gov/",
        "name_suffix": null,
        "contact_form": "http://www.snowe.senate.gov/public/index.cfm/contact?p=email",
        "icpsr_id": 14661,
        "last_name": "Snowe",
        "thomas_id": "01085",
        "in_office": false,
        "lis_id": "S245",
        "middle_name": "J.",
        "youtube_id": "senatorolympiasnowe",
        "facebook_id": "165865453427287",
        "term_start": "2007-01-04",
        "phone": "202-224-5344",
        "district": null,
        "votesmart_id": 26885,
        "govtrack_id": "300091",
        "party": "R"
      },
      "related_bill_ids": [],
      "last_action_at": "2009-11-09",
      "keywords": [
        "Atlantic Ocean",
        "Fishes",
        "International affairs",
        "International law and treaties",
        "Marine and coastal resources, fisheries"
      ],
      "introduced_on": "2009-11-09",
      "sponsor_id": "S000663",
      "short_title": null,
      "urls": {
        "congress": "http://beta.congress.gov/bill/111th/senate-resolution/346",
        "govtrack": "http://www.govtrack.us/congress/bills/111/sres346",
        "opencongress": "http://www.opencongress.org/bill/111-sr346/show"
      },
      "chamber": "senate",
      "official_title": "A resolution expressing the sense of the Senate that, at the 21st Regular Meeting of the International Commission on the Conservation of Atlantic Tunas, the United States should seek to ensure management of the eastern Atlantic and Mediterranean bluefin tuna fishery adheres to the scientific advice provided by the Standing Committee on Research and Statistics and has a high probability of achieving the established rebuilding target, pursue strengthened protections for spawning bluefin populations in the Mediterranean Sea to facilitate the recovery of the Atlantic bluefin tuna, pursue imposition of more stringent measures to ensure compliance by all Members with the International Commission for the Conservation of Atlantic Tunas' conservation and management recommendations for Atlantic bluefin tuna and other species, and ensure that United States' quotas of tuna and swordfish are not reallocated to other nations, and for other purposes.",
      "bill_type": "sres",
      "summary_short": "Expresses the sense of the Senate that the U.S. delegation to the 21st Regular Meeting of the International Commission for the Conservation of Atlantic Tunas should: (1) seek the adoption of all revisions to the multi-annual recovery plan for bluefin tuna in the eastern Atlantic and Mediterranean that will conform the plan to the scientific advice provided by the Standing Committee on Research and Statistics; (2) seek to expand time and area closures of spawning areas in the Mediterranean in conformity with the scientific advice provided by the Standing Committee; (3) pursue the continued review and assessment of compliance; (4) seek to address noncompliance; (5) pursue the commitment by the Commission and its parties to fund additional research on the western Atlantic and eastern Atlantic and Mediterranean bluefin tuna stocks including, but not limited to, the extent to which they mix; and (6) defend U.S. interests with regard to Atlantic bluefin tuna, Atlantic swordfish, and other spe...",
      "search": {
        "score": 0.17215708,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr6434-111",
      "cosponsor_ids": [],
      "sponsor": {
        "birthday": "1966-08-20",
        "bioguide_id": "C001066",
        "gender": "F",
        "fec_ids": [
          "H6FL11126",
          "H6FL11134"
        ],
        "office": "205 Cannon House Office Building",
        "title": "Rep",
        "crp_id": "N00027514",
        "chamber": "house",
        "state_name": "Florida",
        "nickname": null,
        "term_end": "2015-01-03",
        "state": "FL",
        "fax": "202-225-5652",
        "twitter_id": "USRepKCastor",
        "first_name": "Kathy",
        "ocd_id": "ocd-division/country:us/state:fl/cd:14",
        "website": "http://castor.house.gov",
        "name_suffix": null,
        "contact_form": "https://forms.house.gov/wyr/welcome.shtml",
        "icpsr_id": 20708,
        "last_name": "Castor",
        "thomas_id": "01839",
        "in_office": true,
        "middle_name": null,
        "youtube_id": "RepKathyCastor",
        "facebook_id": "181810465190906",
        "term_start": "2013-01-03",
        "phone": "202-225-3376",
        "district": 14,
        "votesmart_id": 53825,
        "govtrack_id": "412195",
        "party": "D"
      },
      "related_bill_ids": [],
      "last_action_at": "2010-12-01",
      "keywords": [
        "Accidents",
        "Air quality",
        "Alternative and renewable resources",
        "Aquatic ecology",
        "Climate change and greenhouse gases",
        "Economic development",
        "Education programs funding",
        "Energy efficiency and conservation",
        "Environmental assessment, monitoring, research",
        "Environmental health",
        "Government trust funds",
        "Gulf of Mexico",
        "Higher education",
        "Marine and coastal resources, fisheries",
        "Marine pollution",
        "Marketing and advertising",
        "Oil and gas",
        "Public lands and natural resources",
        "Research administration and funding",
        "Seafood",
        "Travel and tourism"
      ],
      "introduced_on": "2010-11-18",
      "sponsor_id": "C001066",
      "short_title": "Gulf of Mexico Economic and Environmental Restoration Act of 2010",
      "urls": {
        "congress": "http://beta.congress.gov/bill/111th/house-bill/6434",
        "govtrack": "http://www.govtrack.us/congress/bills/111/hr6434",
        "opencongress": "http://www.opencongress.org/bill/111-h6434/show"
      },
      "chamber": "house",
      "official_title": "To establish programs to aid in the economic, environmental, and public health recovery of the Gulf States from the damage and harm caused by the blowout of the mobile offshore drilling unit Deepwater Horizon and the resulting degradation of the Gulf over time, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Gulf of Mexico Economic and Environmental Restoration Act of 2010 - Establishes the Gulf of Mexico Recovery Council, consisting of each member of the Gulf Coast Ecosystem Restoration Task Force.\n\nDirects the Council to: (1) establish guidelines for, approve or disapprove, and annually review Gulf state comprehensive restoration plans that address the effects in such a state of the oil spill in the Gulf of Mexico caused by the mobile offshore drilling unit Deepwater Horizon that began on April 20, 2010, with regard to the economy, the environment, and public health; (2) distribute funds to states whose plans are approved; (3) establish a Gulf of Mexico Observation System, to be implemented through a Gulf of Mexico Exploration Research Center, to increase observation and monitoring capabilities in the Gulf; (4) establish a Gulf of Mexico sea grant program to fund Gulf coast restoration projects carried out by sea grant colleges or institutions located in the Gulf states (Alabama, Florida,...",
      "search": {
        "score": 0.0797201,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr4480-114",
      "cosponsor_ids": [
        "B001281",
        "B001292",
        "B000574",
        "B001285",
        "C001090",
        "D000191",
        "D000617",
        "D000623",
        "E000288",
        "E000215",
        "F000030",
        "G000559",
        "G000551",
        "H001064",
        "H001068",
        "K000375",
        "K000381",
        "L000551",
        "L000582",
        "L000397",
        "M000312",
        "M001166",
        "N000179",
        "N000147",
        "P000596",
        "P000607",
        "P000598",
        "S001145",
        "S001150",
        "S000510",
        "T000467"
      ],
      "sponsor": {
        "birthday": "1941-03-08",
        "bioguide_id": "L000579",
        "gender": "M",
        "fec_ids": [
          "H2CA00104"
        ],
        "office": "108 Cannon House Office Building",
        "title": "Rep",
        "crp_id": "N00033274",
        "chamber": "house",
        "state_name": "California",
        "nickname": null,
        "term_end": "2017-01-03",
        "state": "CA",
        "fax": "202-225-7926",
        "twitter_id": "RepLowenthal",
        "first_name": "Alan",
        "ocd_id": "ocd-division/country:us/state:ca/cd:47",
        "website": "http://lowenthal.house.gov",
        "name_suffix": null,
        "contact_form": "http://lowenthal.house.gov/contact/howtocontactme.htm",
        "icpsr_id": 21313,
        "last_name": "Lowenthal",
        "thomas_id": "02111",
        "in_office": true,
        "middle_name": "S.",
        "youtube_id": "RepLowenthal",
        "facebook_id": "392631677490897",
        "term_start": "2015-01-06",
        "phone": "202-225-7924",
        "district": 47,
        "votesmart_id": 16469,
        "oc_email": "Rep.Lowenthal@opencongress.org",
        "govtrack_id": "412521",
        "party": "D"
      },
      "related_bill_ids": [],
      "last_action_at": "2016-02-09",
      "keywords": [
        "Administrative law and regulatory procedures",
        "Animals",
        "Aquatic ecology",
        "Birds",
        "Congressional oversight",
        "Department of Commerce",
        "Department of the Interior",
        "Environmental assessment, monitoring, research",
        "Government information and archives",
        "International law and treaties",
        "International organizations and cooperation",
        "Licensing and registrations",
        "Marine and coastal resources, fisheries",
        "Marine pollution",
        "Scientific communication",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2016-02-04",
      "sponsor_id": "L000579",
      "short_title": "Albatross and Petrel Conservation Act",
      "urls": {
        "congress": "http://beta.congress.gov/bill/114th/house-bill/4480",
        "govtrack": "https://www.govtrack.us/congress/bills/114/hr4480",
        "opencongress": "https://www.opencongress.org/bill/hr4480-114"
      },
      "chamber": "house",
      "official_title": "To implement the Agreement on the Conservation of Albatrosses and Petrels, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Albatross and Petrel Conservation Act\n\nThis bill authorizes the United States Fish and Wildlife Service (USFWS) and the National Marine Fisheries Service (NMFS) to promulgate regulations to implement and enforce the Agreement on the Conservation of Albatrosses and Petrels, done at Cape Town, South Africa, on February 2, 2001.\n\nThis bill authorizes USFWS and NMFS to take action to conserve albatrosses and petrels, including to:\n\n reestablish albatrosses and petrels; prevent the introduction of, eradicate, or control invasive and nonnative species that have or may have an adverse effect on albatrosses and petrels; conserve, protect, and restore breeding sites; undertake measures for the conservation and protection of albatross and petrel habitat and other marine habitats that provide food for albatrosses and petrels; undertake scientific research to assess the effects of pollutants and marine debris on albatrosses and petrels; develop and implement measures to prevent, minimize, or mitiga...",
      "search": {
        "score": 0.0797201,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr2494-114",
      "cosponsor_ids": [
        "A000371",
        "B001270",
        "B001292",
        "B000574",
        "B001245",
        "B001296",
        "B001284",
        "C001036",
        "C001037",
        "C001103",
        "C001090",
        "C000266",
        "C001084",
        "C001077",
        "C001068",
        "C001092",
        "C001078",
        "C001094",
        "C001059",
        "C001045",
        "C001063",
        "C001107",
        "D000598",
        "D000191",
        "D000617",
        "D000621",
        "D000623",
        "D000610",
        "D000613",
        "D000625",
        "D000533",
        "E000179",
        "E000215",
        "E000293",
        "F000030",
        "F000451",
        "F000445",
        "F000449",
        "F000462",
        "G000559",
        "G000377",
        "G000551",
        "H001051",
        "H000324",
        "H001065",
        "H001034",
        "H001068",
        "I000057",
        "J000032",
        "K000386",
        "K000375",
        "K000381",
        "K000368",
        "L000551",
        "L000582",
        "L000554",
        "L000565",
        "L000397",
        "L000584",
        "L000579",
        "L000480",
        "L000570",
        "M001179",
        "M001157",
        "M001143",
        "M000312",
        "M001180",
        "M001166",
        "M001197",
        "M001187",
        "M001188",
        "M001144",
        "N000179",
        "N000147",
        "O000170",
        "P000604",
        "P000588",
        "P000608",
        "P000596",
        "P000606",
        "P000607",
        "P000592",
        "P000598",
        "P000523",
        "Q000023",
        "R000053",
        "R000578",
        "R000587",
        "R000602",
        "R000395",
        "R000435",
        "R000604",
        "R000577",
        "S000018",
        "S001145",
        "S001150",
        "S000344",
        "S001165",
        "S000480",
        "S000522",
        "S001196",
        "T000475",
        "V000129",
        "V000131",
        "V000081",
        "W000820",
        "W000799",
        "W000814",
        "W000808",
        "W000795",
        "W000809",
        "Y000065",
        "Z000017"
      ],
      "sponsor": {
        "birthday": "1951-10-12",
        "bioguide_id": "R000487",
        "gender": "M",
        "fec_ids": [
          "H6CA39020"
        ],
        "office": "2310 Rayburn House Office Building",
        "title": "Rep",
        "crp_id": "N00008264",
        "chamber": "house",
        "state_name": "California",
        "nickname": "Ed",
        "term_end": "2017-01-03",
        "state": "CA",
        "fax": "202-226-0335",
        "twitter_id": "RepEdRoyce",
        "first_name": "Edward",
        "ocd_id": "ocd-division/country:us/state:ca/cd:39",
        "website": "http://royce.house.gov",
        "name_suffix": null,
        "contact_form": "https://royce.house.gov/contact/contactform.htm",
        "icpsr_id": 29321,
        "last_name": "Royce",
        "thomas_id": "00998",
        "in_office": true,
        "middle_name": "R.",
        "youtube_id": "RepEdRoyce",
        "facebook_id": "6460640558",
        "term_start": "2015-01-06",
        "phone": "202-225-4111",
        "district": 39,
        "votesmart_id": 26772,
        "oc_email": "Rep.Royce@opencongress.org",
        "govtrack_id": "400348",
        "party": "R"
      },
      "related_bill_ids": [
        "s27-114"
      ],
      "last_action_at": "2016-10-07",
      "keywords": [
        "Africa",
        "Asia",
        "Civil actions and liability",
        "Congressional oversight",
        "Currency",
        "Endangered and threatened species",
        "Foreign aid and international relief",
        "Fraud offenses and financial crimes",
        "International affairs",
        "Law enforcement administration and funding",
        "Law enforcement officers",
        "Mammals",
        "Marine and coastal resources, fisheries",
        "Military assistance, sales, and agreements",
        "Organized crime",
        "Sanctions",
        "Smuggling and trafficking",
        "Travel and tourism",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2015-05-21",
      "sponsor_id": "R000487",
      "short_title": "Eliminate, Neutralize, and Disrupt Wildlife Trafficking Act of 2016",
      "urls": {
        "congress": "http://beta.congress.gov/bill/114th/house-bill/2494",
        "govtrack": "https://www.govtrack.us/congress/bills/114/hr2494",
        "opencongress": "https://www.opencongress.org/bill/hr2494-114"
      },
      "chamber": "house",
      "official_title": "To support global anti-poaching efforts, strengthen the capacity of partner countries to counter wildlife trafficking, designate major wildlife trafficking countries, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Global Anti-Poaching Act\n\nThis bill addresses the illegal trade in endangered and threatened wildlife and their related parts and products.\n\n(Sec 3) The Department of State, the U.S. Agency for International Development, the U.S. Fish and Wildlife Service, and other appropriate agencies are urged to: (1) support strengthening existing wildlife enforcement networks and establishing new networks in other appropriate regions, and (2) promote the professionalization of the wildlife law enforcement sector and professional ranger training in partner countries.\n\n(Sec 5) For the next five years, the State Department must provide to Congress an annual list of each foreign country that is a major source, transit point, or consumer of wildlife trafficking products. The report must designate each country listed in the report that has failed to demonstrably make substantial efforts to adhere to its obligations under international agreements relating to endangered or threatened species. The State Dep...",
      "search": {
        "score": 0.07842586,
        "type": "bill"
      }
    },
    {
      "bill_id": "s3525-112",
      "cosponsor_ids": [
        "B000243",
        "B001265",
        "B001267",
        "C001070",
        "H001049",
        "K000367",
        "M001183",
        "M001170",
        "N000180",
        "P000590",
        "S001181",
        "S000770",
        "U000039",
        "W000805"
      ],
      "sponsor": {
        "birthday": "1956-08-21",
        "bioguide_id": "T000464",
        "gender": "M",
        "fec_ids": [
          "S6MT00162"
        ],
        "office": "706 Hart Senate Office Building",
        "senate_class": 1,
        "title": "Sen",
        "crp_id": "N00027605",
        "chamber": "senate",
        "state_name": "Montana",
        "nickname": null,
        "term_end": "2019-01-03",
        "state": "MT",
        "fax": "202-224-8594",
        "twitter_id": "testerpress",
        "first_name": "Jon",
        "ocd_id": "ocd-division/country:us/state:mt",
        "website": "http://www.tester.senate.gov",
        "name_suffix": null,
        "contact_form": "http://www.tester.senate.gov/Contact/index.cfm",
        "icpsr_id": 40702,
        "last_name": "Tester",
        "thomas_id": "01829",
        "in_office": true,
        "lis_id": "S314",
        "middle_name": null,
        "youtube_id": "senatorjontester",
        "facebook_id": "210573031664",
        "state_rank": "junior",
        "term_start": "2013-01-03",
        "phone": "202-224-2644",
        "district": null,
        "votesmart_id": 20928,
        "govtrack_id": "412244",
        "party": "D"
      },
      "related_bill_ids": [
        "hr991-112",
        "hr1829-112",
        "hr3065-112",
        "hr3117-112",
        "hr3365-112",
        "hr3510-112",
        "hr6441-112",
        "s714-112",
        "s899-112",
        "s1066-112",
        "s1201-112",
        "s1249-112",
        "s1494-112",
        "s2071-112",
        "s3422-112"
      ],
      "last_action_at": "2012-11-26",
      "keywords": [
        "Advisory bodies",
        "Animal protection and human-animal relationships",
        "Appropriations",
        "Aquatic ecology",
        "Art, artists, authorship",
        "Birds",
        "Canada",
        "Chesapeake Bay",
        "Congressional oversight",
        "Delaware",
        "Ecology",
        "Endangered and threatened species",
        "Firearms and explosives",
        "Fishes",
        "Forests, forestry, trees",
        "Government liability",
        "Government trust funds",
        "Gulf of Mexico",
        "Hawaii",
        "Hazardous wastes and toxic substances",
        "Hunting and fishing",
        "Indian lands and resources rights",
        "Land transfers",
        "Land use and conservation",
        "Licensing and registrations",
        "Louisiana",
        "Mammals",
        "Marine and coastal resources, fisheries",
        "Maryland",
        "North Carolina",
        "Oregon",
        "Outdoor recreation",
        "Parks, recreation areas, trails",
        "Postal service",
        "Public lands and natural resources",
        "Public-private cooperation",
        "Reptiles",
        "Social work, volunteer service, charitable organizations",
        "Solid waste and recycling",
        "Sports and recreation facilities",
        "State and local government operations",
        "Tax-exempt organizations",
        "Trade restrictions",
        "U.S. territories and protectorates",
        "Virginia",
        "Washington State",
        "Wetlands",
        "Wilderness and natural areas, wildlife refuges, wild rivers, habitats",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2012-09-10",
      "sponsor_id": "T000464",
      "short_title": "Sportsmen's Act of 2012",
      "urls": {
        "congress": "http://beta.congress.gov/bill/112th/senate-bill/3525",
        "govtrack": "http://www.govtrack.us/congress/bills/112/s3525",
        "opencongress": "http://www.opencongress.org/bill/112-s3525/show"
      },
      "chamber": "senate",
      "official_title": "A bill to protect and enhance opportunities for recreational hunting, fishing, and shooting, and for other purposes.",
      "bill_type": "s",
      "summary_short": "Sportsmen's Act of 2012 - Amends the Land and Water Conservation Fund Act of 1965 to direct the Secretary of the Interior and the Secretary of Agriculture (USDA) to ensure that not less than 1.5% of the amounts made available for the Land and Water Conservation Fund for each fiscal year shall be made available for certain projects identified on an annual priority list to be developed pursuant to this Act. Requires such projects to secure, through rights-of-way or the acquisition of lands or interests from willing sellers, recreational public access to existing federal public lands that have significantly restricted access to hunting, fishing, and other recreational purposes.\n\nAmends the Marine Mammal Protection Act of 1972 to direct the Secretary of the Interior to issue a permit for the importation of any polar bear part (other than an internal organ) from a polar bear taken in a sport hunt in Canada to any person who meets specified requirements.\n\nRequires the Secretary of the Interio...",
      "search": {
        "score": 0.047834553,
        "type": "bill"
      }
    },
    {
      "bill_id": "hr1870-112",
      "cosponsor_ids": [
        "B001242",
        "E000215",
        "L000557",
        "M000133",
        "W000215"
      ],
      "sponsor": {
        "birthday": "1950-03-30",
        "bioguide_id": "C001078",
        "gender": "M",
        "fec_ids": [
          "H8VA11062"
        ],
        "office": "424 Cannon House Office Building",
        "title": "Rep",
        "crp_id": "N00029891",
        "chamber": "house",
        "state_name": "Virginia",
        "nickname": null,
        "term_end": "2015-01-03",
        "state": "VA",
        "fax": "202-225-3071",
        "twitter_id": "GerryConnolly",
        "first_name": "Gerald",
        "ocd_id": "ocd-division/country:us/state:va/cd:11",
        "website": "http://connolly.house.gov",
        "name_suffix": null,
        "contact_form": "https://forms.house.gov/connolly/contact-form.shtml",
        "icpsr_id": 20952,
        "last_name": "Connolly",
        "thomas_id": "01959",
        "in_office": true,
        "middle_name": "E.",
        "youtube_id": "repconnolly",
        "facebook_id": "177164035838",
        "term_start": "2013-01-03",
        "phone": "202-225-1492",
        "district": 11,
        "votesmart_id": 95078,
        "govtrack_id": "412272",
        "party": "D"
      },
      "related_bill_ids": [
        "hr56-112",
        "hr501-112",
        "hr503-112",
        "hr927-112",
        "hr1568-112",
        "hr2260-112",
        "hr3562-112",
        "s1140-112"
      ],
      "last_action_at": "2011-09-08",
      "keywords": [
        "Accidents",
        "Administrative law and regulatory procedures",
        "Administrative remedies",
        "Advanced technology and technological innovations",
        "Advisory bodies",
        "Alaska",
        "Alternative and renewable resources",
        "Aquatic ecology",
        "Business records",
        "Buy American requirements",
        "Coast guard",
        "Department of Defense",
        "Department of Homeland Security",
        "Department of Transportation",
        "Department of the Interior",
        "Employment discrimination and employee rights",
        "Energy",
        "Energy research",
        "Energy revenues and royalties",
        "Energy storage, supplies, demand",
        "Environmental Protection Agency (EPA)",
        "Environmental assessment, monitoring, research",
        "Environmental health",
        "Environmental technology",
        "Executive agency funding and structure",
        "Government employee pay, benefits, personnel management",
        "Government ethics and transparency, public corruption",
        "Government information and archives",
        "Government studies and investigations",
        "Government trust funds",
        "Great Lakes",
        "Gulf of Mexico",
        "Hazardous wastes and toxic substances",
        "Indian lands and resources rights",
        "Intergovernmental relations",
        "International organizations and cooperation",
        "Judicial review and appeals",
        "Labor-management relations",
        "Licensing and registrations",
        "Mammals",
        "Marine and coastal resources, fisheries",
        "Marine and inland water transportation",
        "Marine pollution",
        "Oil and gas",
        "Pipelines",
        "Pollution liability",
        "Research administration and funding",
        "Research and development",
        "State and local government operations",
        "Strategic materials and reserves",
        "Technology assessment",
        "User charges and fees",
        "Water quality",
        "Wilderness and natural areas, wildlife refuges, wild rivers, habitats",
        "Wildlife conservation and habitat protection"
      ],
      "introduced_on": "2011-05-12",
      "sponsor_id": "C001078",
      "short_title": "Increase American Energy Production Now Act of 2011",
      "urls": {
        "congress": "http://beta.congress.gov/bill/112th/house-bill/1870",
        "govtrack": "http://www.govtrack.us/congress/bills/112/hr1870",
        "opencongress": "http://www.opencongress.org/bill/112-h1870/show"
      },
      "chamber": "house",
      "official_title": "To safely increase domestic oil and gas production, and for other purposes.",
      "bill_type": "hr",
      "summary_short": "Increase American Energy Production Now Act of 2011 - Establishes in the Department of the Interior: (1) a Bureau of Ocean Energy Management to administer a program of offshore energy and mineral resources management on the Outer Continental Shelf (OCS), (2) a Bureau of Safety and Environmental Enforcement to administer safety and environmental enforcement activities related to such resources, (3) a National Oil and Gas Health and Safety Academy to train Department of the Interior personnel, and (4) an Office of Natural Resources Revenue to administer offshore royalty and revenue management functions. Abolishes the Minerals Management Service and transfers specified functions to such Bureaus and Office.\n\nRequires the Secretary of the Interior to: (1) certify compliance with federal employee ethics laws annually; and (2) establish an Outer Continental Shelf Safety and Environmental Advisory Board to advise the Secretary and the Directors of such Bureaus on safe and environmentally compli...",
      "search": {
        "score": 0.023917276,
        "type": "bill"
      }
    }
  ]
}
